<?xml version="1.0"?>
<package format="3">
  <name>openamrobot_upperbody_gazebo</name>
  <version>0.0.0</version>
  <description>Gazebo simulation of the combined model.</description>
  <maintainer email="info@botshare.ai">OpenAMRobot</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>openamrobot_upperbody_description</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
