<?xml version="1.0"?>
<package format="3">
  <name>openamrobot_upperbody_moveit</name>
  <version>0.0.0</version>
  <description>MoveIt 2 config (planning groups: arm, arm+lift).</description>
  <maintainer email="info@botshare.ai">OpenAMRobot</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>openamrobot_upperbody_description</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
